#!/bin/bash
#
# Startup script for the tomcat
#
# chkconfig: 345 80 15
# description: Tomcat is a Servlet+JSP Engine.

# Source function library.
#. /etc/rc.d/init.d/functions


export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/apr/lib

JAVA_HOME=/usr/java/jdk1.8.0_121

CATALINA_HOME=/var/tomcat

export JAVA_HOME CATALINA_HOME



start(){
#if [ -z "$(/sbin/pidof java)" ]; then
echo "Starting tomcat"
su -c /var/tomcat/bin/startup.sh tomcat
touch /var/lock/subsys/tomcat
#else
#echo "tomcat allready running"
#fi
}

stop(){
if [ ! -z "$(/sbin/pidof java)" ]; then
echo "Shutting down tomcat"
killall -9 java
until [ -z "$(/sbin/pidof java)" ]; do :; done
rm -f /var/lock/subsys/tomcat
else
echo "tomcat not running"
fi
}

case "$1" in
start)
start
;;
stop)
stop
;;
restart)
stop
start
;;
status)
/var/tomcat/bin/catalina.sh version
;;
*)
echo "Usage: $0 {start|stop|restart|status}"
esac

exit 0
